name: build-packer-images

on:
  push:
    branches:
      - main

env:
  LOCATION: SoutheastAsia
  DESTINATION_RESOURCE_GROUP_NAME: anarcill-images
  DESTINATION_IMAGE_GALLERY_NAME: anarcillsharedimages
  DESTINATION_PUBLISHER: Miguel.Arcilla
  DESTINATION_IMAGE_VERSION: 1.0.${{ github.run_number }}
  AZURE_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
  AZURE_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
  AZURE_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
  AZURE_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}

jobs:
  prepare-image-gallery:
    runs-on: ubuntu-latest
    name: Prepare Image Gallery

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Image Gallery Template
        uses: azure/CLI@v1
        with:
          azcliversion: 2.24.2
          inlineScript: |
            az account show
            date=$(date +"%Y%m%d%H%M")
            az deployment sub create \
              --name "imageGallery-${date}" \
              --location $LOCATION \
              --template-file bicep/main.bicep \
              --parameters location="$LOCATION" resourceGroupName="$DESTINATION_RESOURCE_GROUP_NAME" imageGalleryName="$DESTINATION_IMAGE_GALLERY_NAME"

  build-image:
    runs-on: ubuntu-latest
    name: Build Image
    needs: prepare-image-gallery
    strategy:
      # Limit parallel builds so don't use all Azure core quota
      max-parallel: 3
      matrix:
        image_id: [Windows-Server-2016,Windows-Server-2019,Windows-10-Enterprise]
        include:
          - image_id: Windows-Server-2016
            packer_file: "packer/microsoft-windows.pkr.hcl"
            destination_image_name: MicrosoftWindowsServer2016DatacenterVsCode
            destination_image_description: Windows Server 2016 Datacenter with VS Code
            source_image_publisher: MicrosoftWindowsServer
            source_image_offer: WindowsServer
            source_image_sku: 2016-Datacenter
            destination_os_type: Windows
            destination_offer: WindowsServerVsCode
            destination_sku: 2016-Datacenter

          - image_id: Windows-Server-2019
            packer_file: "packer/microsoft-windows.pkr.hcl"
            destination_image_name: MicrosoftWindowsServer2019DatacenterVsCode
            destination_image_description: Windows Server 2019 Datacenter with VS Code
            source_image_publisher: MicrosoftWindowsServer
            source_image_offer: WindowsServer
            source_image_sku: 2019-Datacenter
            destination_os_type: Windows
            destination_offer: WindowsServerVsCode
            destination_sku: 2019-Datacenter

          - image_id: Windows-10-Enterprise
            packer_file: "packer/microsoft-windows.pkr.hcl"
            destination_image_name: MicrosoftWindowsDesktop1020h1entDatacenterVsCode
            destination_image_description: Windows 10 20h1-ent with VS Code
            source_image_publisher: MicrosoftWindowsDesktop
            source_image_offer: Windows-10
            source_image_sku: 20h1-ent
            destination_os_type: Windows
            destination_offer: Windows10VsCode
            destination_sku: 20h1-ent
    env:
      PACKER_FILE: ${{ matrix.packer_file }}
      DESTINATION_IMAGE_NAME: ${{ matrix.destination_image_name }}
      DESTINATION_IMAGE_DESCRIPTION: ${{ matrix.destination_image_description }}
      SOURCE_IMAGE_PUBLISHER: ${{ matrix.source_image_publisher }}
      SOURCE_IMAGE_OFFER: ${{ matrix.source_image_offer }}
      SOURCE_IMAGE_SKU: ${{ matrix.source_image_sku }}
      DESTINATION_OS_TYPE: ${{ matrix.destination_os_type }}
      DESTINATION_OFFER: ${{ matrix.destination_offer }}
      DESTINATION_SKU: ${{ matrix.destination_sku }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: "-syntax-only"
          target: ${{ env.PACKER_FILE }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Image Definition
        uses: azure/CLI@v1
        with:
          azcliversion: 2.24.2
          inlineScript: |
            az account show
            date=$(date +"%Y%m%d%H%M")
            az deployment group create \
              --name "${DESTINATION_IMAGE_NAME}-${date}" \
              --resource-group $DESTINATION_RESOURCE_GROUP_NAME \
              --template-file bicep/modules/imageDefinition.bicep \
              --parameters location="$LOCATION" imageGalleryName="$DESTINATION_IMAGE_GALLERY_NAME" imageDefinitionName="$DESTINATION_IMAGE_NAME" osType="$DESTINATION_OS_TYPE" imageDescription="$DESTINATION_IMAGE_DESCRIPTION" publisher="$DESTINATION_PUBLISHER" offer="$DESTINATION_OFFER" sku="$DESTINATION_SKU"

      - name: Build Image Definition
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort -var azure_subscription_id=${{ env.AZURE_SUBSCRIPTION_ID }} -var azure_tenant_id=${{ env.AZURE_TENANT_ID }} -var azure_client_id=${{ env.AZURE_CLIENT_ID }} -var azure_client_secret=${{ env.AZURE_CLIENT_SECRET }} -var location=${{ env.LOCATION }} -var destination_resource_group_name=${{ env.DESTINATION_RESOURCE_GROUP_NAME }} -var destination_image_gallery_name=${{ env.DESTINATION_IMAGE_GALLERY_NAME }} -var destination_image_name=${{ env.DESTINATION_IMAGE_NAME }} -var destination_image_version=${{ env.DESTINATION_IMAGE_VERSION }} -var source_image_publisher=${{ env.SOURCE_IMAGE_PUBLISHER }} -var source_image_offer=${{ env.SOURCE_IMAGE_OFFER }} -var source_image_sku=${{ env.SOURCE_IMAGE_SKU }}"
          target: ${{ env.PACKER_FILE }}
        env:
          PACKER_LOG: 1
