name: build-packer-images

on:
  push:
    branches:
      - main

env:
  LOCATION: SoutheastAsia
  DESTINATION_RESOURCE_GROUP_NAME: anarcill-images
  DESTINATION_IMAGE_GALLERY_NAME: anarcillsharedimages
  DESTINATION_PUBLISHER: Miguel.Arcilla
  DESTINATION_IMAGE_VERSION: 1.0.${{ github.run_number }}
  AZURE_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
  AZURE_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
  AZURE_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
  AZURE_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}

jobs:
  prepare-image-gallery:
    runs-on: ubuntu-latest
    name: Prepare Image Gallery

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Image Gallery Template
        uses: azure/CLI@v1
        with:
          azcliversion: 2.24.2
          inlineScript: |
            az account show
            date=$(date +"%Y%m%d%H%M")
            az deployment sub create \
              --name "imageGallery-${date}" \
              --location $LOCATION \
              --template-file bicep/main.bicep \
              --parameters location="$LOCATION" resourceGroupName="$DESTINATION_RESOURCE_GROUP_NAME" imageGalleryName="$DESTINATION_IMAGE_GALLERY_NAME"

  build-MicrosoftWindowsServer2016DatacenterVsCode:
    runs-on: ubuntu-latest
    needs: prepare-image-gallery
    name: Build Microsoft Windows Server 2016-Datacenter with VS Code
    env:
      PACKER_FILE: "packer/microsoft-windows.pkr.hcl"
      DESTINATION_IMAGE_NAME: MicrosoftWindowsServer2016DatacenterVsCode
      DESTINATION_IMAGE_DESCRIPTION: "Windows Server 2016 Datacenter with VS Code"
      SOURCE_IMAGE_PUBLISHER: "MicrosoftWindowsServer"
      SOURCE_IMAGE_OFFER: "WindowsServer"
      SOURCE_IMAGE_SKU: "2016-Datacenter"
      DESTINATION_OS_TYPE: Windows
      DESTINATION_OFFER: "WindowsServerVsCode"
      DESTINATION_SKU: "2016-Datacenter"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: "-syntax-only"
          target: ${{ env.PACKER_FILE }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Image Definition
        uses: azure/CLI@v1
        with:
          azcliversion: 2.24.2
          inlineScript: |
            az account show
            date=$(date +"%Y%m%d%H%M")
            az deployment group create \
              --name "${DESTINATION_IMAGE_NAME}-${date}" \
              --resource-group $DESTINATION_RESOURCE_GROUP_NAME \
              --template-file bicep/modules/imageDefinition.bicep \
              --parameters location="$LOCATION" imageGalleryName="$DESTINATION_IMAGE_GALLERY_NAME" imageDefinitionName="$DESTINATION_IMAGE_NAME" osType="$DESTINATION_OS_TYPE" imageDescription="$DESTINATION_IMAGE_DESCRIPTION" publisher="$DESTINATION_PUBLISHER" offer="$DESTINATION_OFFER" sku="$DESTINATION_SKU"

      - name: Build Image Definition
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort -var azure_subscription_id=${{ env.AZURE_SUBSCRIPTION_ID }} -var azure_tenant_id=${{ env.AZURE_TENANT_ID }} -var azure_client_id=${{ env.AZURE_CLIENT_ID }} -var azure_client_secret=${{ env.AZURE_CLIENT_SECRET }} -var location=${{ env.LOCATION }} -var destination_resource_group_name=${{ env.DESTINATION_RESOURCE_GROUP_NAME }} -var destination_image_gallery_name=${{ env.DESTINATION_IMAGE_GALLERY_NAME }} -var destination_image_name=${{ env.DESTINATION_IMAGE_NAME }} -var destination_image_version=${{ env.DESTINATION_IMAGE_VERSION }} -var source_image_publisher=${{ env.SOURCE_IMAGE_PUBLISHER }} -var source_image_offer=${{ env.SOURCE_IMAGE_OFFER }} -var source_image_sku=${{ env.SOURCE_IMAGE_SKU }}"
          target: ${{ env.PACKER_FILE }}
        env:
          PACKER_LOG: 1

  build-MicrosoftWindowsServer2019DatacenterVsCode:
    runs-on: ubuntu-latest
    needs: prepare-image-gallery
    name: Build Microsoft Windows Server 2019-Datacenter with VS Code
    env:
      PACKER_FILE: "packer/microsoft-windows.pkr.hcl"
      DESTINATION_IMAGE_NAME: MicrosoftWindowsServer2019DatacenterVsCode
      DESTINATION_IMAGE_DESCRIPTION: "Windows Server 2019 Datacenter with VS Code"
      SOURCE_IMAGE_PUBLISHER: "MicrosoftWindowsServer"
      SOURCE_IMAGE_OFFER: "WindowsServer"
      SOURCE_IMAGE_SKU: "2019-Datacenter"
      DESTINATION_OS_TYPE: Windows
      DESTINATION_OFFER: "WindowsServerVsCode"
      DESTINATION_SKU: "2019-Datacenter"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: "-syntax-only"
          target: ${{ env.PACKER_FILE }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Image Definition
        uses: azure/CLI@v1
        with:
          azcliversion: 2.24.2
          inlineScript: |
            az account show
            date=$(date +"%Y%m%d%H%M")
            az deployment group create \
              --name "${DESTINATION_IMAGE_NAME}-${date}" \
              --resource-group $DESTINATION_RESOURCE_GROUP_NAME \
              --template-file bicep/modules/imageDefinition.bicep \
              --parameters location="$LOCATION" imageGalleryName="$DESTINATION_IMAGE_GALLERY_NAME" imageDefinitionName="$DESTINATION_IMAGE_NAME" osType="$DESTINATION_OS_TYPE" imageDescription="$DESTINATION_IMAGE_DESCRIPTION" publisher="$DESTINATION_PUBLISHER" offer="$DESTINATION_OFFER" sku="$DESTINATION_SKU"

      - name: Build Image Definition
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort -var azure_subscription_id=${{ env.AZURE_SUBSCRIPTION_ID }} -var azure_tenant_id=${{ env.AZURE_TENANT_ID }} -var azure_client_id=${{ env.AZURE_CLIENT_ID }} -var azure_client_secret=${{ env.AZURE_CLIENT_SECRET }} -var location=${{ env.LOCATION }} -var destination_resource_group_name=${{ env.DESTINATION_RESOURCE_GROUP_NAME }} -var destination_image_gallery_name=${{ env.DESTINATION_IMAGE_GALLERY_NAME }} -var destination_image_name=${{ env.DESTINATION_IMAGE_NAME }} -var destination_image_version=${{ env.DESTINATION_IMAGE_VERSION }} -var source_image_publisher=${{ env.SOURCE_IMAGE_PUBLISHER }} -var source_image_offer=${{ env.SOURCE_IMAGE_OFFER }} -var source_image_sku=${{ env.SOURCE_IMAGE_SKU }}"
          target: ${{ env.PACKER_FILE }}
        env:
          PACKER_LOG: 1

  build-MicrosoftWindows1020h1entVsCode:
    runs-on: ubuntu-latest
    needs: prepare-image-gallery
    name: Build Microsoft Windows 10 20h1-ent with VS Code
    env:
      PACKER_FILE: "packer/microsoft-windows.pkr.hcl"
      DESTINATION_IMAGE_NAME: MicrosoftWindowsDesktop1020h1entDatacenterVsCode
      DESTINATION_IMAGE_DESCRIPTION: "Windows 10 20h1-ent with VS Code"
      SOURCE_IMAGE_PUBLISHER: "MicrosoftWindowsDesktop"
      SOURCE_IMAGE_OFFER: "Windows-10"
      SOURCE_IMAGE_SKU: "20h1-ent"
      DESTINATION_OS_TYPE: Windows
      DESTINATION_OFFER: "Windows10VsCode"
      DESTINATION_SKU: "20h1-ent"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: "-syntax-only"
          target: ${{ env.PACKER_FILE }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Image Definition
        uses: azure/CLI@v1
        with:
          azcliversion: 2.24.2
          inlineScript: |
            az account show
            date=$(date +"%Y%m%d%H%M")
            az deployment group create \
              --name "${DESTINATION_IMAGE_NAME}-${date}" \
              --resource-group $DESTINATION_RESOURCE_GROUP_NAME \
              --template-file bicep/modules/imageDefinition.bicep \
              --parameters location="$LOCATION" imageGalleryName="$DESTINATION_IMAGE_GALLERY_NAME" imageDefinitionName="$DESTINATION_IMAGE_NAME" osType="$DESTINATION_OS_TYPE" imageDescription="$DESTINATION_IMAGE_DESCRIPTION" publisher="$DESTINATION_PUBLISHER" offer="$DESTINATION_OFFER" sku="$DESTINATION_SKU"

      - name: Build Image Definition
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort -var azure_subscription_id=${{ env.AZURE_SUBSCRIPTION_ID }} -var azure_tenant_id=${{ env.AZURE_TENANT_ID }} -var azure_client_id=${{ env.AZURE_CLIENT_ID }} -var azure_client_secret=${{ env.AZURE_CLIENT_SECRET }} -var location=${{ env.LOCATION }} -var destination_resource_group_name=${{ env.DESTINATION_RESOURCE_GROUP_NAME }} -var destination_image_gallery_name=${{ env.DESTINATION_IMAGE_GALLERY_NAME }} -var destination_image_name=${{ env.DESTINATION_IMAGE_NAME }} -var destination_image_version=${{ env.DESTINATION_IMAGE_VERSION }} -var source_image_publisher=${{ env.SOURCE_IMAGE_PUBLISHER }} -var source_image_offer=${{ env.SOURCE_IMAGE_OFFER }} -var source_image_sku=${{ env.SOURCE_IMAGE_SKU }}"
          target: ${{ env.PACKER_FILE }}
        env:
          PACKER_LOG: 1
